
# This is a TOML document. Boom~
[base]
    version="v1.0.0"
    env="dev"
    token=""
    keyid=""
    screet=""
[http]
    addr = "0.0.0.0:38705"
    timeout = "1s"

[userHttpClient]
    key    = "11111"
    secret = "1111122222"
    dial      = "500ms"
    timeout   = "2s"
    keepAlive = "30s"
    timer = 10
    [userHttpClient.breaker]
        window  = "10s"
        sleep   = "100ms"
        bucket  = 10
        ratio   = 0.5
        request = 100


[rpcClient2]
    [rpcClient2.user]
        timeout = "1s"
     [rpcClient2.stream]
            timeout = "1s"

[mysql]
	addr = "192.168.57.110:18066"
	dsn = "root:rootfabric@tcp(192.168.57.110:18066)/TESTDB?timeout=1s&readTimeout=1s&writeTimeout=1s&parseTime=true&loc=Local&charset=utf8mb4,utf8"
	readDSN = ["root:rootfabric@tcp(192.168.57.110:18066)/TESTDB?timeout=1s&readTimeout=1s&writeTimeout=1s&parseTime=true&loc=Local&charset=utf8mb4,utf8"]
	active = 20
	idle = 10
	idleTimeout ="4h"
	queryTimeout = "200ms"
	execTimeout = "300ms"
	tranTimeout = "400ms"

[redis]
    name = "kratos-getaway-servers"
	proto = "tcp"
	addr = "192.168.57.136:19000"
	idle = 10
	active = 10
	dialTimeout = "1s"
	readTimeout = "1s"
	writeTimeout = "1s"
	idleTimeout = "10s"

[expire]
    redisExpire = "24h"

[log]
    family = "app-log"
    stdout=true
    dir = "/Users/a747/Documents/logs/app-log"
    [log.agent]
        addr = "/tmp/log/unix_sock"
#        addr = "/tmp/unix_sock"
        timeout = "1s"
        network = "unix"

[tracer]
     # addr = "192.168.57.134:16686"
      addr = "/tmp/trace/unix_sock"
      timeout = "30s"
      network = "unix"
      protocolVersion = 1
      probability = 0.5