
demoExpire = "24h"

[demo]
	name = "user-acount-server"
	proto = "tcp"
	addr = "192.168.57.134:19000"
	idle = 10
	active = 10
	dialTimeout = "1s"
	readTimeout = "1s"
	writeTimeout = "1s"
	idleTimeout = "10s"
