
[demo]
	addr = "192.168.57.110:18066"
	dsn = "root:rootfabric@tcp(192.168.57.110:18066)/TESTDB?timeout=1s&readTimeout=1s&writeTimeout=1s&parseTime=true&loc=Local&charset=utf8mb4,utf8"
	readDSN = ["root:rootfabric@tcp(192.168.57.110:18066)/TESTDB?timeout=1s&readTimeout=1s&writeTimeout=1s&parseTime=true&loc=Local&charset=utf8mb4,utf8"]
	active = 20
	idle = 10
	idleTimeout ="4h"
	queryTimeout = "200ms"
	execTimeout = "300ms"
	tranTimeout = "400ms"
