
demoExpire = "24h"

[demo]
	name = "user-getaway-servers"
	proto = "tcp"
	addr = "192.168.57.136:19000"
	idle = 10
	active = 10
	dialTimeout = "1s"
	readTimeout = "1s"
	writeTimeout = "1s"
	idleTimeout = "10s"
